
import React,{useEffect,useMemo,useState} from "react";
import {AlertTriangle,BarChart3,CheckCircle2,ChevronRight,CloudRain,Clock3,Compass,IndianRupee,Info,MapPin,Menu,RefreshCw,Route,ShieldCheck,Truck,Users,Wind,X,Phone,FileText,Settings as SettingsIcon,Radio,Navigation,Send,AlertCircle} from "lucide-react";

const API="http://localhost:8000";
type RouteData={id:string,name:string,distance:number,time_min:number,estimated_time:string,risk:number,risk_category:string,accessibility:number,reliability:number,cost:{fuel:number,tolls:number,operations:number,total:number},route_score:number,weather:{rainfall:number,severity:number,condition:string},contributors:Record<string,number>,breakdown:Record<string,number>,points:number[][]};

function riskClass(n:number){return n<=30?"low":n<=60?"moderate":n<=80?"high":"critical"}
function riskLabel(n:number){return n<=30?"Low":n<=60?"Moderate":n<=80?"High":"Critical"}

const demoRoutes:RouteData[]=[];
function App(){
 const [page,setPage]=useState("Dashboard"),[mobile,setMobile]=useState(false);
 const [source,setSource]=useState("Guwahati"),[destination,setDestination]=useState("Itanagar");
 const [vehicle,setVehicle]=useState("Heavy Truck"),[cargo,setCargo]=useState("Medicine"),[weight,setWeight]=useState("5"),[priority,setPriority]=useState("Safest");
 const [routes,setRoutes]=useState<RouteData[]>(demoRoutes),[recommended,setRecommended]=useState<RouteData|null>(null),[explanation,setExplanation]=useState("");
 const [loading,setLoading]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState("A"),[disrupted,setDisrupted]=useState(false);
 const [alerts,setAlerts]=useState<any[]>([]),[analytics,setAnalytics]=useState<any>(null),[regions,setRegions]=useState<any[]>([]),[vehicles,setVehicles]=useState<any[]>([]),[incidents,setIncidents]=useState<any[]>([]),[fieldReports,setFieldReports]=useState<any[]>([]);
 useEffect(()=>{fetch(API+"/api/alerts").then(r=>r.json()).then(setAlerts).catch(()=>{});fetch(API+"/api/analytics").then(r=>r.json()).then(setAnalytics).catch(()=>{});fetch(API+"/api/regions").then(r=>r.json()).then(setRegions).catch(()=>{});fetch(API+"/api/vehicles").then(r=>r.json()).then(setVehicles).catch(()=>{});fetch(API+"/api/incidents").then(r=>r.json()).then(setIncidents).catch(()=>{});fetch(API+"/api/field-reports").then(r=>r.json()).then(setFieldReports).catch(()=>{});},[]);
 async function analyze(){
   setError("");setLoading(true);setDisrupted(false);
   try{const res=await fetch(API+"/api/routes/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source,destination,vehicle_type:vehicle,cargo_type:cargo,cargo_weight:Number(weight),priority})});
   const data=await res.json(); if(!res.ok) throw new Error(data.detail||"Unable to analyze route"); setRoutes(data.routes);setRecommended(data.recommended);setExplanation(data.explanation);setSelected(data.recommended.id);setPage("Route Planner");
   }catch(e:any){setError(e.message+" — start the FastAPI backend first.");}finally{setLoading(false)}
 }
 async function recalc(){
   if(!recommended)return; setLoading(true);
   try{const res=await fetch(API+"/api/routes/recalculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({routes,disrupted_route_id:recommended.id})});const data=await res.json();setRoutes(data.routes);setRecommended(data.recommended);setExplanation(data.message+" It adds approximately "+data.additional_time+" minutes and ₹"+data.additional_cost+" in this demo.");setSelected(data.recommended.id);setDisrupted(true);}
   finally{setLoading(false)}
 }
 const selectedRoute=routes.find(r=>r.id===selected)||recommended;
 return <div className="app">
  <aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="logo"><Route size={22}/></div><div><b>NEXUS NER</b><span>Logistics Intelligence</span></div></div>
   <nav>{[["Dashboard",BarChart3],["Route Planner",Compass],["Live Map",Navigation],["Vehicles",Truck],["Incidents",AlertTriangle],["Field Reports",FileText],["Live Alerts",AlertTriangle],["Analytics",BarChart3],["Regional Risk",MapPin],["Emergency Help",Phone],["Settings",SettingsIcon]].map(([name,I]:any)=><button key={name} className={page===name?"nav active":"nav"} onClick={()=>{setPage(name);setMobile(false)}}><I size={18}/>{name}</button>)}</nav>
   <div className="side-card"><ShieldCheck size={20}/><b>AI Risk Engine</b><p>Random Forest prototype model online</p><small>● Operational</small></div>
  </aside>
  <main className="main"><header><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><div className="eyebrow">NORTH EASTERN REGION • INTELLIGENCE PLATFORM</div><h1>{page}</h1></div><div className="profile"><div className="avatar">SV</div><span>Operations</span></div></header>
   {error&&<div className="error"><X size={17}/>{error}</div>}
   {page==="Dashboard"&&<Dashboard setPage={setPage} analyze={analyze} alerts={alerts} analytics={analytics}/>}
   {page==="Route Planner"&&<Planner source={source} setSource={setSource} destination={destination} setDestination={setDestination} vehicle={vehicle} setVehicle={setVehicle} cargo={cargo} setCargo={setCargo} weight={weight} setWeight={setWeight} priority={priority} setPriority={setPriority} analyze={analyze} loading={loading} routes={routes} recommended={recommended} explanation={explanation} selected={selected} setSelected={setSelected} selectedRoute={selectedRoute} recalc={recalc} disrupted={disrupted}/>}
   {page==="Live Map"&&<LiveMap vehicles={vehicles} incidents={incidents}/>}
   {page==="Vehicles"&&<Vehicles vehicles={vehicles}/>}
   {page==="Incidents"&&<Incidents incidents={incidents} setIncidents={setIncidents}/>}
   {page==="Field Reports"&&<FieldReports reports={fieldReports} setReports={setFieldReports}/>}
   {page==="Live Alerts"&&<Alerts alerts={alerts}/>}
   {page==="Analytics"&&<Analytics data={analytics}/>}
   {page==="Regional Risk"&&<Regions regions={regions}/>}
   {page==="Emergency Help"&&<EmergencyHelp/>}
   {page==="Settings"&&<SettingsPage/>}
  </main>
 </div>
}

function Dashboard({setPage,analyze,alerts,analytics}:any){return <section>
 <div className="hero"><div><div className="pill"><ShieldCheck size={15}/> AI-POWERED ROUTE RISK</div><h2>Move freight through the Northeast<br/><em>with intelligence.</em></h2><p>Risk-aware logistics planning that combines weather, terrain, road conditions, accessibility and historical disruption intelligence.</p><div className="hero-actions"><button className="primary" onClick={()=>setPage("Route Planner")}>Plan a Route <ChevronRight size={17}/></button><button className="secondary" onClick={analyze}>Run Demo Analysis</button></div></div><div className="hero-art"><div className="radar"></div><div className="radar-dot d1"></div><div className="radar-dot d2"></div><div className="route-line"></div><Truck className="truck" size={30}/><span className="map-label l1">GUWAHATI</span><span className="map-label l2">ITANAGAR</span></div></div>
 <div className="stats">{[["Active Routes","28","↑ 12% this week",Route],["High Risk Routes","06","2 need attention",AlertTriangle],["Weather Alerts","14","4 severe",CloudRain],["Road Disruptions","09","3 new today",AlertTriangle],["Avg Risk Score","52 / 100","Moderate",ShieldCheck],["AI Cost Savings","₹2.84L","14.8% estimated",IndianRupee]].map(([a,b,c,I]:any)=><div className="stat"><div className="stat-icon"><I size={18}/></div><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>
 <div className="grid2"><div className="panel"><div className="panel-head"><div><b>Regional risk overview</b><small>Current prototype intelligence</small></div><button onClick={()=>setPage("Regional Risk")}>View map <ChevronRight size={15}/></button></div><div className="mini-regions">{["Assam","Arunachal Pradesh","Meghalaya","Manipur","Mizoram"].map((x,i)=><div><span>{x}</span><div className="bar"><i style={{width:(42+i*7)+"%"}}/></div><b>{42+i*7}</b></div>)}</div></div>
 <div className="panel"><div className="panel-head"><div><b>Priority alerts</b><small>Latest disruptions</small></div><button onClick={()=>setPage("Live Alerts")}>All alerts <ChevronRight size={15}/></button></div>{alerts.slice(0,3).map((a:any)=><div className="alert-row"><span className={"severity "+a.severity.toLowerCase()}></span><div><b>{a.type}</b><small>{a.location} • {a.time}</small></div><strong>{a.severity}</strong></div>)}</div></div>
 </section>}

function Planner(p:any){return <section>
 <div className="planner-grid"><div className="panel form-panel"><div className="panel-head"><div><b>Route configuration</b><small>Define your freight movement</small></div><Truck size={19}/></div>
  <label>Source<input value={p.source} onChange={e=>p.setSource(e.target.value)} placeholder="e.g. Guwahati"/></label>
  <label>Destination<input value={p.destination} onChange={e=>p.setDestination(e.target.value)} placeholder="e.g. Itanagar"/></label>
  <div className="two"><label>Vehicle<select value={p.vehicle} onChange={e=>p.setVehicle(e.target.value)}><option>Mini Truck</option><option>Light Commercial Vehicle</option><option>Heavy Truck</option><option>Container Truck</option><option>Emergency Vehicle</option></select></label><label>Cargo<select value={p.cargo} onChange={e=>p.setCargo(e.target.value)}><option>General Goods</option><option>Food</option><option>Medicine</option><option>Construction Material</option><option>Perishable Goods</option></select></label></div>
  <label>Cargo weight <span className="unit">tonnes</span><input type="number" min="0" value={p.weight} onChange={e=>p.setWeight(e.target.value)}/></label>
  <label>Priority</label><div className="priorities">{["Fastest","Cheapest","Safest","Balanced"].map((x)=><button className={p.priority===x?"priority chosen":"priority"} onClick={()=>p.setPriority(x)}><b>{x}</b><small>{x==="Safest"?"Minimize risk":x==="Fastest"?"Minimize time":x==="Cheapest"?"Minimize cost":"Best trade-off"}</small></button>)}</div>
  <button className="primary full" onClick={p.analyze} disabled={p.loading}>{p.loading?<><RefreshCw className="spin"/>Analyzing...</>:"Analyze Routes"}</button>
 </div>
 <div className="map-panel"><div className="map-top"><div><span className="pill">LIVE ROUTE MODEL</span><b>{p.recommended?"AI route analysis":"Northeast route intelligence"}</b></div><div className="map-legend"><span><i className="dot rec"></i>Recommended</span><span><i className="dot alt"></i>Alternative</span><span><i className="dot risk"></i>Risk zone</span></div></div><RouteMap routes={p.routes} selected={p.selected} setSelected={p.setSelected} source={p.source} destination={p.destination}/></div></div>
 {p.recommended&&<><div className="recommend"><div className="rec-badge"><ShieldCheck size={18}/> AI RECOMMENDED ROUTE</div><div className="rec-main"><div><h3>{p.recommended.name}</h3><p>{p.explanation}</p></div><div className="score-ring"><b>{p.recommended.route_score}</b><span>Route score</span></div></div>{p.disrupted&&<div className="disruption"><AlertTriangle size={18}/><div><b>Route disruption detected</b><span>Landslide risk changed the ranking. The recommendation has been recalculated.</span></div></div>}</div>
 <div className="result-head"><div><h2>Route alternatives</h2><span>{p.routes.length} routes evaluated • {p.priority} priority</span></div>{!p.disrupted&&<button className="danger-btn" onClick={p.recalc}><AlertTriangle size={16}/> Simulate Landslide</button>}</div>
 <div className="route-cards">{p.routes.map((r:RouteData)=><RouteCard r={r} chosen={p.selected===r.id} onClick={()=>p.setSelected(r.id)}/>)}</div>
 <div className="compare panel"><div className="panel-head"><div><b>Route comparison</b><small>Normalized route intelligence</small></div></div><table><thead><tr><th>Metric</th>{p.routes.map((r:RouteData)=><th className={r.id===p.recommended.id?"rec-col":""}>{r.id}</th>)}</tr></thead><tbody>{[["Distance",...p.routes.map((r:RouteData)=>r.distance+" km")],["Time",...p.routes.map((r:RouteData)=>r.estimated_time)],["Cost",...p.routes.map((r:RouteData)=>"₹"+r.cost.total.toLocaleString())],["Risk",...p.routes.map((r:RouteData)=>r.risk)],["Accessibility",...p.routes.map((r:RouteData)=>r.accessibility)],["Reliability",...p.routes.map((r:RouteData)=>r.reliability)]].map((row:any)=><tr>{row.map((c:any,i:number)=><td className={i===0?"metric":""}>{c}</td>)}</tr>)}</tbody></table></div>
 </>}
 </section>}

function RouteMap({routes,selected,setSelected,source,destination}:any){const selectedRoute=routes.find((r:any)=>r.id===selected);return <div className="map"><div className="map-water"></div><div className="map-grid"></div>{routes.map((r:any)=><svg className="route-svg" viewBox="0 0 340 260"><polyline points={r.points.map((p:any)=>p.join(",")).join(" ")} className={r.id===selected?"route selected":"route"}/></svg>)}<div className="risk-zone z1"></div><div className="risk-zone z2"></div><div className="marker source" style={{left:"25%",top:"25%"}}><MapPin size={25}/><span>{source}</span></div><div className="marker destination" style={{left:"73%",top:"64%"}}><MapPin size={25}/><span>{destination}</span></div><div className="hazard h1"><AlertTriangle size={13}/></div><div className="hazard h2"><CloudRain size={13}/></div><div className="map-card">{selectedRoute?<><b>{selectedRoute.name}</b><span>{selectedRoute.distance} km • {selectedRoute.estimated_time}</span><strong className={"risk-text "+riskClass(selectedRoute.risk)}>{selectedRoute.risk}/100 {riskLabel(selectedRoute.risk)}</strong></>:<span>Select a route to inspect details</span>}</div></div>}

function RouteCard({r,chosen,onClick}:any){return <button className={chosen?"route-card chosen":"route-card"} onClick={onClick}><div className="route-card-top"><div><span className="route-id">{r.id}</span><div><b>{r.name}</b><small>{r.weather.condition} • {r.weather.rainfall} mm rainfall index</small></div></div>{chosen&&<CheckCircle2 size={20}/>}</div><div className="metrics"><Metric icon={Route} label="Distance" value={r.distance+" km"}/><Metric icon={Clock3} label="Time" value={r.estimated_time}/><Metric icon={IndianRupee} label="Cost" value={"₹"+r.cost.total.toLocaleString()}/><Metric icon={ShieldCheck} label="Risk" value={r.risk+"/100"} cls={riskClass(r.risk)}/></div><div className="bars"><Bar label="Accessibility" n={r.accessibility}/><Bar label="Reliability" n={r.reliability}/></div></button>}
function Metric({icon:Icon,label,value,cls=""}:any){return <div><Icon size={15}/><small>{label}</small><b className={cls}>{value}</b></div>}
function Bar({label,n}:any){return <div className="barline"><span>{label}</span><i><em style={{width:n+"%"}}/></i><b>{n}</b></div>}

function Alerts({alerts}:any){return <section><div className="page-intro"><div><h2>Live route alerts</h2><p>Prototype disruption intelligence across NER corridors.</p></div><div className="alert-count"><AlertTriangle/> {alerts.length} active</div></div><div className="alert-list">{alerts.map((a:any)=><div className="alert-card"><div className={"alert-symbol "+a.severity.toLowerCase()}><AlertTriangle size={19}/></div><div className="alert-info"><div><span className={"badge "+a.severity.toLowerCase()}>{a.severity} risk</span><b>{a.type}</b></div><h3>{a.location}</h3><p>{a.impact} • Affected: {a.route}</p><small>Reported {a.time}</small></div><ChevronRight/></div>)}</div></section>}

function Analytics({data}:any){if(!data)return <div className="loading">Loading analytics...</div>;return <section><div className="page-intro"><div><h2>Logistics analytics</h2><p>Portfolio-level performance and risk indicators.</p></div></div><div className="stats">{[["Routes analyzed",data.routes_analyzed,"lifetime"],["Average risk",data.average_risk+"/100","moderate"],["Avg. cost","₹"+data.average_cost.toLocaleString(),"estimated"],["Reliability",data.reliability+"/100","network"],["Disruptions",data.disruptions,"recorded"],["AI savings",data.cost_savings+"%","estimated"]].map(([a,b,c]:any)=><div className="stat"><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className="chart-grid"><Chart title="Risk trend" data={data.risk_trend}/><Chart title="Disruption frequency" data={data.disruption_chart}/><Chart title="Cost comparison" data={data.cost_comparison}/><Chart title="Reliability by route" data={data.reliability_chart}/></div></section>}
function Chart({title,data}:any){const max=Math.max(...data);return <div className="panel chart"><div className="panel-head"><b>{title}</b><Info size={15}/></div><div className="bars-chart">{data.map((n:number,i:number)=><div><i style={{height:(n/max*100)+"%"}}></i><span>{n}</span></div>)}</div></div>}

function Regions({regions}:any){return <section><div className="page-intro"><div><h2>Regional risk intelligence</h2><p>Eight NER states • synthetic prototype indicators.</p></div></div><div className="region-grid">{regions.map((r:any)=><div className="region-card"><div className="region-top"><div className={"state-icon "+riskClass(r.risk)}><MapPin size={18}/></div><div><b>{r.name}</b><small>{r.disruptions} recent disruptions</small></div><strong className={"risk-text "+riskClass(r.risk)}>{r.risk}</strong></div><div className="risk-bar"><i style={{width:r.risk+"%"}}/></div><div className="region-meta"><span>Accessibility <b>{r.accessibility}</b></span><span>Major hazards <b>{r.hazards.join(", ")}</b></span></div></div>)}</div></section>}



function FleetMap({vehicles,incidents}:{vehicles:any[],incidents:any[]}){return <div className="fleet-map map"><div className="map-water"></div><div className="map-grid"></div><div className="region-label r1">ASSAM</div><div className="region-label r2">MEGHALAYA</div><div className="region-label r3">ARUNACHAL PRADESH</div><div className="region-label r4">NAGALAND</div>{vehicles.map((v:any,i:number)=><div key={v.id} className="fleet-marker" style={{left:`${18+i*15}%`,top:`${27+(i%3)*17}%`}} title={v.id}><Truck size={18}/><span>{v.id}</span></div>)}{incidents.slice(0,5).map((a:any,i:number)=><div key={a.id} className="incident-marker" style={{left:`${45+(i%3)*12}%`,top:`${25+(i%4)*14}%`}}><AlertTriangle size={15}/></div>)}<div className="map-card"><b>Fleet & incident overview</b><span>{vehicles.length} vehicles • {incidents.length} incidents</span><strong>Prototype operational map</strong></div></div>}

function LiveMap({vehicles,incidents}:any){return <section><div className="page-intro"><div><h2>Live map</h2><p>Operational view of fleet vehicles and reported incidents across NER.</p></div><div className="alert-count"><Radio/> Prototype feed</div></div><div className="panel"><div className="panel-head"><div><b>Fleet map</b><small>Vehicle positions and incident markers</small></div><span className="map-legend"><i className="dot rec"></i>Vehicle &nbsp; <i className="dot risk"></i>Incident</span></div><FleetMap vehicles={vehicles} incidents={incidents}/></div></section>}

function Vehicles({vehicles}:any){return <section><div className="page-intro"><div><h2>Vehicle tracking</h2><p>Fleet status, capacity and driver information.</p></div><div className="alert-count"><Truck/> {vehicles.length} vehicles</div></div><div className="panel"><div className="panel-head"><div><b>Fleet map</b><small>Prototype locations • not live GPS</small></div></div><FleetMap vehicles={vehicles} incidents={[]}/></div><div className="fleet-grid">{vehicles.map((v:any)=><div className="fleet-card" key={v.id}><div className="fleet-head"><div className="fleet-id"><Truck size={17}/><b>{v.id}</b></div><span className={'status '+v.status.toLowerCase().replace(' ','-')}>{v.status}</span></div><p>{v.type} • capacity {v.capacity_kg} kg</p><p>Driver: {v.driver}</p><small>Updated {v.updated}</small></div>)}</div></section>}

function Incidents({incidents,setIncidents}:any){const [type,setType]=useState('Landslide'),[description,setDescription]=useState(''),[lat,setLat]=useState('25.58'),[lng,setLng]=useState('91.89'),[severity,setSeverity]=useState('Medium'),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');async function submit(){setSaving(true);setMsg('');try{const r=await fetch(API+'/api/incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({incident_type:type,description,latitude:Number(lat),longitude:Number(lng),severity})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Unable to submit');setIncidents((x:any[])=>[d,...x]);setMsg('Incident submitted successfully.');setDescription('')}catch(e:any){setMsg(e.message)}finally{setSaving(false)}}return <section><div className="page-intro"><div><h2>Incidents</h2><p>Report and monitor disruptions affecting logistics routes.</p></div></div><div className="two-col"><div className="panel"><div className="panel-head"><div><b>Incident map</b><small>Reported locations</small></div></div><div className="incident-mini-map"><div className="map-grid"></div>{incidents.map((a:any,i:number)=><div className="incident-pin" key={a.id} style={{left:`${22+(i*19)%68}%`,top:`${22+(i*23)%60}%`}}><AlertTriangle size={17}/></div>)}</div></div><div className="panel form-panel"><div className="panel-head"><div><b>Report an incident</b><small>Create a new operational alert</small></div></div><label>Incident type<select value={type} onChange={e=>setType(e.target.value)}><option>Landslide</option><option>Flood</option><option>Road blockage</option><option>Accident</option><option>Heavy rainfall</option><option>Road construction</option><option>Traffic congestion</option></select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe what was observed..."/></label><div className="two"><label>Latitude<input value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input value={lng} onChange={e=>setLng(e.target.value)}/></label></div><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><button className="primary full" onClick={submit} disabled={saving}>{saving?'Submitting...':'Submit incident'}</button>{msg&&<div className="success-msg">{msg}</div>}</div></div><div className="panel incident-list"><div className="panel-head"><div><b>All incidents</b><small>Latest field and operational reports</small></div></div>{incidents.map((a:any)=><div className="incident-row" key={a.id}><div className={'alert-symbol '+a.severity.toLowerCase()}><AlertTriangle size={18}/></div><div><b>{a.type}</b><h3>{a.location}</h3><p>{a.description}</p><small>{a.severity} • {a.status} • {a.reported}</small></div></div>)}</div></section>}

function FieldReports({reports,setReports}:any){const [reporter,setReporter]=useState('Field Unit 08'),[location,setLocation]=useState('Bomdila'),[type,setType]=useState('Road condition'),[severity,setSeverity]=useState('Medium'),[description,setDescription]=useState('');async function submit(){const r=await fetch(API+'/api/field-reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reporter,location,report_type:type,severity,description})});const d=await r.json();if(r.ok){setReports((x:any[])=>[d,...x]);setDescription('')}}return <section><div className="page-intro"><div><h2>Field reports</h2><p>Capture observations from field teams and road crews.</p></div></div><div className="two-col"><div className="panel form-panel"><div className="panel-head"><div><b>Submit field report</b><small>Feeds operational intelligence</small></div><Send size={18}/></div><label>Reporter<input value={reporter} onChange={e=>setReporter(e.target.value)}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><div className="two"><label>Report type<select value={type} onChange={e=>setType(e.target.value)}><option>Road condition</option><option>Traffic</option><option>Weather</option><option>Flood</option><option>Landslide</option><option>Accident</option></select></label><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label></div><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Field observation..."/></label><button className="primary full" onClick={submit}>Submit report</button></div><div className="panel"><div className="panel-head"><div><b>Recent field reports</b><small>Operational submissions</small></div></div><div className="report-list">{reports.map((r:any)=><div className="report-card" key={r.id}><div className="report-top"><b>{r.id}</b><span className={'badge '+r.severity.toLowerCase()}>{r.severity}</span></div><h3>{r.location}</h3><p>{r.type} • {r.reporter}</p><p>{r.description}</p><small>{r.status} • {r.time}</small></div>)}</div></div></div></section>}

function EmergencyHelp(){const states=['Assam','Arunachal Pradesh','Meghalaya','Manipur','Mizoram','Nagaland','Tripura','Sikkim'];const [state,setState]=useState('Assam'),[contacts,setContacts]=useState<any[]>([]);useEffect(()=>{fetch(API+'/api/emergency/'+encodeURIComponent(state)).then(r=>r.json()).then(setContacts).catch(()=>{})},[state]);return <section><div className="page-intro"><div><h2>Emergency help</h2><p>Emergency contacts by NER state/region.</p></div></div><div className="notice"><AlertCircle size={17}/><span>Numbers marked <b>demo</b> are prototype placeholders. Verify official state contacts before real-world use. National helplines 112 and 108 are included as genuine national services.</span></div><label className="state-select">State / region<select value={state} onChange={e=>setState(e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select></label><div className="contact-grid">{contacts.map((c:any)=><div className="contact-card" key={c.category}><small>{c.category}</small><div><div><b>{c.name}</b></div><strong>{c.number}</strong>{c.demo&&<span className="demo-tag">demo</span>}</div></div>)}</div></section>}

function SettingsPage(){const [refresh,setRefresh]=useState(true),[demo,setDemo]=useState(true);return <section><div className="page-intro"><div><h2>Settings</h2><p>Prototype configuration and data controls.</p></div></div><div className="panel settings-panel"><div className="setting-row"><div><b>Prototype data mode</b><small>Use synthetic data when live APIs are unavailable.</small></div><input type="checkbox" checked={demo} onChange={e=>setDemo(e.target.checked)}/></div><div className="setting-row"><div><b>Auto-refresh operational feeds</b><small>Refresh vehicle, incident and alert data when the page loads.</small></div><input type="checkbox" checked={refresh} onChange={e=>setRefresh(e.target.checked)}/></div><div className="setting-row"><div><b>ML engine</b><small>Random Forest regression model using synthetic prototype training data.</small></div><span className="status on-time">Operational</span></div><div className="setting-row"><div><b>Map provider</b><small>Self-contained prototype visualization; no paid API key required.</small></div><span className="status on-time">Local</span></div></div></section>}

export default App;
